# spring
spring:
#   datasource
  datasource:
    # druid
#    druid:
    url: jdbc:oracle:thin:@127.0.0.1:1521/ORCL
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
#      max-active: 10
#      max-wait: 10000
#      min-idle: 5
#      initial-size: 5
#      test-on-borrow: false
#      test-while-idle: true